; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nodemcu-32s

[env]
platform = espressif32@6.12.0
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
monitor_eol = LF

[env:nodemcu-32s]
build_src_filter = -<*> +<main.cpp>

[env:motor-only]
build_src_filter = -<*> +<motor_only.cpp>
